import { StyleSheet } from '@react-pdf/renderer';

export const AURA_PDF = {
  green: '#16B57D',
  greenDark: '#12966A',
  orange: '#F2A021',
  night: '#0A0A0F',
  slate: '#70757F',
  muted: '#94a3b8',
  border: '#e2e8f0',
  white: '#ffffff',
  critical: '#dc2626',
  warning: '#b45309',
  excellent: '#3d7a57',
} as const;

export const auraPdfStyles = StyleSheet.create({
  page: {
    paddingTop: 0,
    paddingBottom: 48,
    paddingHorizontal: 40,
    fontSize: 10,
    fontFamily: 'Helvetica',
    color: AURA_PDF.night,
  },
  headerBar: {
    backgroundColor: AURA_PDF.green,
    marginHorizontal: -40,
    paddingHorizontal: 40,
    paddingVertical: 20,
    marginBottom: 20,
  },
  brandRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  brandTitle: {
    fontSize: 22,
    fontFamily: 'Helvetica-Bold',
    color: AURA_PDF.white,
    letterSpacing: 1,
  },
  brandTagline: {
    fontSize: 9,
    color: AURA_PDF.white,
    marginTop: 4,
    opacity: 0.9,
  },
  reportType: {
    fontSize: 11,
    color: AURA_PDF.white,
    textAlign: 'right',
    fontFamily: 'Helvetica-Bold',
  },
  reportId: {
    fontSize: 8,
    color: AURA_PDF.white,
    textAlign: 'right',
    marginTop: 4,
  },
  sectionTitle: {
    fontSize: 12,
    fontFamily: 'Helvetica-Bold',
    color: AURA_PDF.greenDark,
    marginTop: 14,
    marginBottom: 8,
    paddingBottom: 4,
    borderBottomWidth: 1,
    borderBottomColor: AURA_PDF.green,
  },
  subsection: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
    marginTop: 8,
    marginBottom: 4,
    color: AURA_PDF.night,
  },
  paragraph: {
    fontSize: 10,
    lineHeight: 1.45,
    marginBottom: 6,
    color: '#334155',
  },
  metaGrid: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    marginBottom: 8,
  },
  metaCell: {
    width: '48%',
    marginBottom: 6,
  },
  metaLabel: {
    fontSize: 8,
    color: AURA_PDF.slate,
    textTransform: 'uppercase',
    marginBottom: 2,
  },
  metaValue: {
    fontSize: 10,
    fontFamily: 'Helvetica-Bold',
  },
  kpiRow: {
    flexDirection: 'row',
    marginVertical: 8,
  },
  kpiBox: {
    flex: 1,
    padding: 10,
    backgroundColor: '#f0fdf4',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: AURA_PDF.green,
  },
  kpiBoxSpaced: {
    flex: 1,
    padding: 10,
    marginLeft: 8,
    backgroundColor: '#f0fdf4',
    borderRadius: 4,
    borderWidth: 1,
    borderColor: AURA_PDF.green,
  },
  headerBarCompact: {
    backgroundColor: AURA_PDF.green,
    marginHorizontal: -40,
    paddingHorizontal: 40,
    paddingVertical: 12,
    marginBottom: 16,
  },
  headerBarPlan: {
    backgroundColor: AURA_PDF.greenDark,
    marginHorizontal: -40,
    paddingHorizontal: 40,
    paddingVertical: 12,
    marginBottom: 16,
  },
  headerCompactTitle: {
    fontSize: 14,
    fontFamily: 'Helvetica-Bold',
    color: AURA_PDF.white,
  },
  kpiLabel: {
    fontSize: 8,
    color: AURA_PDF.slate,
  },
  kpiValue: {
    fontSize: 16,
    fontFamily: 'Helvetica-Bold',
    color: AURA_PDF.greenDark,
    marginTop: 2,
  },
  bullet: {
    flexDirection: 'row',
    marginBottom: 4,
    paddingLeft: 4,
  },
  bulletDot: {
    width: 12,
    fontSize: 10,
    color: AURA_PDF.green,
  },
  bulletText: {
    flex: 1,
    fontSize: 9,
    lineHeight: 1.4,
    color: '#334155',
  },
  findingBox: {
    marginBottom: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: AURA_PDF.border,
    borderRadius: 4,
    backgroundColor: '#fafafa',
  },
  findingTitle: {
    fontSize: 11,
    fontFamily: 'Helvetica-Bold',
    color: AURA_PDF.night,
    marginBottom: 4,
  },
  badgeWrap: {
    backgroundColor: AURA_PDF.orange,
    paddingHorizontal: 6,
    paddingVertical: 3,
    borderRadius: 3,
    alignSelf: 'flex-start',
    marginBottom: 6,
  },
  badgeText: {
    fontSize: 8,
    color: AURA_PDF.white,
  },
  paragraphSmall: {
    fontSize: 9,
    lineHeight: 1.45,
    marginBottom: 6,
    color: '#334155',
  },
  footerNote: {
    marginTop: 16,
  },
  footer: {
    position: 'absolute',
    bottom: 20,
    left: 40,
    right: 40,
    flexDirection: 'row',
    justifyContent: 'space-between',
    borderTopWidth: 1,
    borderTopColor: AURA_PDF.border,
    paddingTop: 8,
  },
  footerText: {
    fontSize: 7,
    color: AURA_PDF.slate,
  },
  disclaimer: {
    fontSize: 8,
    color: AURA_PDF.slate,
    fontStyle: 'italic',
    marginTop: 12,
    lineHeight: 1.4,
    padding: 8,
    backgroundColor: '#f8fafc',
    borderRadius: 4,
  },
});
